apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"graylog"},"name":"graylog","namespace":"logging"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"graylog"}},"template":{"metadata":{"labels":{"app":"graylog"}},"spec":{"containers":[{"env":[{"name":"GRAYLOG_ROOT_PASSWORD_SHA2","valueFrom":{"secretKeyRef":{"key":"graylog-root-password-sha2","name":"graylog-secrets"}}},{"name":"GRAYLOG_ROOT_USERNAME","value":"root"},{"name":"GRAYLOG_HTTP_BIND_ADDRESS","value":"0.0.0.0:9000"},{"name":"GRAYLOG_PASSWORD_SECRET","value":"long-random-string-for-graylog-salt"},{"name":"GRAYLOG_MONGODB_URI","value":"mongodb://mongodb-service:27017/graylog?replicaSet=rs0"},{"name":"GRAYLOG_ELASTICSEARCH_HOSTS","value":"http://elasticsearch:9200"}],"image":"graylog/graylog:4.3","name":"graylog","ports":[{"containerPort":9000}]}]}}}}
  creationTimestamp: "2025-09-23T07:38:07Z"
  generation: 1
  labels:
    app: graylog
  name: graylog
  namespace: logging
  resourceVersion: "534780569"
  uid: a746a7d6-6a48-4d5f-a1ff-460599da5438
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: graylog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: graylog
    spec:
      containers:
      - env:
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          valueFrom:
            secretKeyRef:
              key: graylog-root-password-sha2
              name: graylog-secrets
        - name: GRAYLOG_ROOT_USERNAME
          value: root
        - name: GRAYLOG_HTTP_BIND_ADDRESS
          value: 0.0.0.0:9000
        - name: GRAYLOG_PASSWORD_SECRET
          value: long-random-string-for-graylog-salt
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongodb-service:27017/graylog?replicaSet=rs0
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        image: graylog/graylog:4.3
        imagePullPolicy: IfNotPresent
        name: graylog
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-09-23T07:38:08Z"
    lastUpdateTime: "2025-09-23T07:38:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-09-23T07:38:07Z"
    lastUpdateTime: "2025-09-23T07:38:08Z"
    message: ReplicaSet "graylog-7bdcc57d96" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
